name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.name != 'actions'
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn build
      - run: yarn keycloak
      - uses: actions/upload-artifact@v2
        with:
          name: keycloak_theme
          path: build_keycloak/target/*keycloak-theme*.jar
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  check_if_version_upgraded:
    name: Check if version upgrade
    runs-on: ubuntu-latest
    needs: build
    outputs:
      from_version: ${{ steps.step1.outputs.from_version }}
      to_version: ${{ steps.step1.outputs.to_version }}
      is_upgraded_version: ${{ steps.step1.outputs.is_upgraded_version }}
    steps:
      - uses: garronej/github_actions_toolkit@v2.2
        id: step1
        with:
          action_name: is_package_json_version_upgraded

  update_changelog:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' &&
      needs.check_if_version_upgraded.outputs.is_upgraded_version == 'true'
    steps:
      - uses: garronej/github_actions_toolkit@v2.4
        with:
          action_name: update_changelog
          branch: ${{ github.ref }}

  release:
    runs-on: ubuntu-latest
    needs:
      - update_changelog
      - check_if_version_upgraded
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/download-artifact@v2
        with:
          name: keycloak_theme
      - run: mv *keycloak-theme*.jar keycloak-theme.jar
      - name: Build GitHub release body
        id: step1
        run: |
          if [ "$FROM_VERSION" = "0.0.0" ]; then
              echo "::set-output name=body::🚀"
          else
              echo "::set-output name=body::📋 [CHANGELOG](https://github.com/$GITHUB_REPOSITORY/blob/v$TO_VERSION/CHANGELOG.md)"
          fi
        env:
          FROM_VERSION: ${{ needs.check_if_version_upgraded.outputs.from_version }}
          TO_VERSION: ${{ needs.check_if_version_upgraded.outputs.to_version }}
      - uses: garronej/action-gh-release@v0.2.0
        with:
          name: Release v${{ needs.check_if_version_upgraded.outputs.to_version }}
          tag_name: v${{ needs.check_if_version_upgraded.outputs.to_version }}
          target_commitish: ${{ github.ref }}
          files: keycloak-theme.jar
          body: ${{ steps.step1.outputs.body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
